version: '3'

services:
  web:
    restart: always
    build: .
    volumes:
      - .:/code
      # temp upload dir (need share w/ nginx)
      - ./_files:/var/www/_files
      # final upload dir (need share w/ nginx)
      - ./files:/var/www/files

  nginx:
    restart: always
    build: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # temp upload dir (need share w/ web)
      - ./_files:/var/www/_files
      # final upload dir (need share w/ web)
      - ./files:/var/www/files
      # - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
